{
 "title": "Login Producer Service - Kafka Consumer Metrics",
 "tags": [
  "kafka",
  "consumer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumed rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(consumer_processed_count_total[1m]))"
    }
   ]
  },
  {
   "title": "Avg processing latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(rate(consumer_processing_latency_seconds_sum{topic=\"customer-data\"}[5m]) / rate(consumer_processing_latency_seconds_count{topic=\"customer-data\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "p95 processing latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(consumer_processing_latency_seconds_bucket{topic=\"customer-data\"}[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "Processed total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(consumer_processed_count_total{topic=\"customer-data\"})"
    }
   ]
  }
 ]
}